# Generated by Django 5.2 on 2025-04-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentification", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identity",
            name="image",
            field=models.FileField(upload_to="ids/"),
        ),
    ]
