# Generated by Django 5.2 on 2025-04-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentification", "0002_alter_identity_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identity",
            name="image",
            field=models.ImageField(upload_to="ids/"),
        ),
    ]
