# Generated by Django 5.2 on 2025-04-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentification", "0003_alter_identity_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identity",
            name="expiry_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
