# Generated by Django 5.2 on 2025-04-24 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentification", "0004_alter_identity_expiry_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="identity",
            name="user",
        ),
    ]
