# Generated by Django 5.2 on 2025-04-24 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentification", "0005_remove_identity_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="identity",
            old_name="id_number",
            new_name="number_piece",
        ),
        migrations.RenameField(
            model_name="identity",
            old_name="id_type",
            new_name="type_piece",
        ),
    ]
